name: createExtensionsV1beta1NamespacedIngress
pack: kubernetes
runner_type: run-python
description: "create an Ingress"
enabled: true
entry_point: "createExtensionsV1beta1NamespacedIngress.py"
parameters:
    body:
        type: object
        description: ""
        required: True
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
    config_override:
        type: object
        description: "override stackstorm config"
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
