name: readExtensionsV1beta1NamespacedIngress
pack: kubernetes
runner_type: python-script
description: "read the specified Ingress"
enabled: true
entry_point: "readExtensionsV1beta1NamespacedIngress.py"
parameters:
    config_override:
        type: object
        description: "override stackstorm config"
        secret: true
    name:
        type: string
        description: "name of the Ingress"
        required: True
        
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
        
    exact:
        type: boolean
        description: "Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'."
        
    export:
        type: boolean
        description: "Should this value be exported.  Export strips fields that a user can not specify."
        
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
        