name: readCoreV1NamespacedConfigMap
pack: kubernetes
runner_type: run-python
description: "read the specified ConfigMap"
enabled: true
entry_point: "readCoreV1NamespacedConfigMap.py"
parameters:
    name:
        type: string
        description: "name of the ConfigMap"
        required: True
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
    config_override:
        type: object
        description: "override stackstorm config"
    exact:
        type: boolean
        description: "Should the export be exact.  Exact export maintains cluster-specific fields like 'Namespace'"
    export:
        type: boolean
        description: "Should this value be exported.  Export strips fields that a user can not specify."
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
