name: replaceExtensionsV1beta1NamespacedDeployment
pack: kubernetes
runner_type: run-python
description: "replace the specified Deployment"
enabled: true
entry_point: "replaceExtensionsV1beta1NamespacedDeployment.py"
parameters:
    body:
        type: object
        description: ""
        required: True
    name:
        type: string
        description: "name of the Deployment"
        required: True
    namespace:
        type: string
        description: "object name and auth scope, such as for teams and projects"
        required: True
    config_override:
        type: object
        description: "override stackstorm config"
    pretty:
        type: string
        description: "If 'true', then the output is pretty printed."
